#!/usr/bin/env python3

from getpass import getpass
from moneylib.remote.mbna import MBNAConnection

username = input('Username: ')
password = getpass()
mbna = MBNAConnection(username, password, 'sitekey')
mbna.get_transactions(1, 2)

# from moneylib.remote.common import xvfb
# from selenium import webdriver

# with xvfb():
#     driver = webdriver.Firefox()
#     driver.get("http://www.google.com/")
#     print(driver.title)
#     driver.quit()
